export default {
  LOGOTYPE_ALT: 'NetflixRoulette',
  FILTER_ALL_TAG_CAPTION: 'All',
  SEARCH_TITLE: 'Find your movie',
  SEARCH_PLACEHOLDER: 'What do you want to watch?',
  SEARCH_BUTTON: 'Search',
  SORT_BY_CAPTION: 'Sort by',
  RELEASE_DATE: 'Release date',
  RATING: 'Rating',
  BUTTON_ADD_MOVIE: 'Add movie',
  BUTTON_EDIT: 'Edit',
  BUTTON_DELETE: 'Delete',
  BUTTON_CONFIRM: 'Confirm',
  POPUP_TITLE_EDIT_MOVIE: 'Edit movie',
  POPUP_TITLE_ADD_MOVIE: 'Add movie',
  POPUP_TITLE_DELETE_MOVIE: 'Delete movie',
  POPUP_TEXT_DELETE_MOVIE: 'Are you sure you want to delete this movie?',
  NOTIFICATION_TITLE_SUCCESS: 'Congratulations!',
  NOTIFICATION_MESSAGE_SUCCESS_FOR_EDIT_MOVIE: 'The movie has been edited successfully',
  NOTIFICATION_MESSAGE_SUCCESS_FOR_ADD_MOVIE: 'The movie has been added to database successfully',
  NOTIFICATION_MESSAGE_SUCCESS_FOR_DELETE_MOVIE: 'The movie has been deleted successfully',
  ERROR_TEXT: 'Something went wrong. Please try again later',
  PAGE_NOT_FOUND_TITLE: 'Oops! 404 page not found...',
  PAGE_NOT_FOUND_TEXT: 'We can`t find the page you are looking for. Go ',
  PAGE_NOT_FOUND_LINK_HOME: 'home',
  NO_RESULT_SEARCH: 'Sorry! No result found :(',
};
